version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.2
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres2020
          POSTGRES_DB: graphqltest
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Waiting for postgres to be ready
          command: |
            for i in `seq 1 10`
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: yarn server:ci
